apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      run: petclinic
  template:
    metadata:
      labels:
        run: petclinic
    spec:
      containers:
        - image: harbor.mgmt.tkg-vsphere-lab.winterfell.live/petclinic/petclinic@sha256:21b8c57850abcaef76d15db080437bdc9d24b85c5fb80a09967e6b33219307ab
          name: petclinic
